env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - XCPROJ="-workspace SwiftElm.xcworkspace -scheme SwiftElm"

matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build -destination 'platform=iOS Simulator,name=iPhone 6s' ENABLE_TESTABILITY=YES $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-iOS
